version: '3.7'
services:
  store:
    image: ${IMAGE_PREFIX}cnxta/ion-store
    ports:
      - target: 8080
        published: 9041
        protocol: tcp
      - target: 10051
        published: 10051
        protocol: tcp
    environment:
      RETRIEVE_HOST: ${RETRIEVE_HOST}
      S3_PROVIDER_URL: ${S3_PROVIDER_URL}
      S3_REGION: ${S3_REGION}
    networks:
      - cdr
    deploy:
      restart_policy:
        condition: any
    secrets:
      - source: s3_secret
        target: /secrets/store/s3_secret.sec
      - source: s3_access
        target: /secrets/store/s3_access.sec
    command:
      - "--s3.secret.file=/secrets/store/s3_secret.sec"
      - "--s3.access.file=/secrets/store/s3_access.sec"
networks:
  cdr:
    external: true
secrets:
  s3_secret:
    file: s3_secret.sec
  s3_access:
    file: s3_access.sec