version: 2.1
jobs:
  Full build without itests:
    machine:
      image: circleci/classic:latest
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Install java 11
          command:
            sudo apt-get -y install openjdk-11-jdk
      - run:
          name: Set default java 11
          command:
            sudo update-java-alternatives --set java-1.11.0-openjdk-amd64
      - run:
          name: Building
          command: |
            ./gradlew clean build --info
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
  OWASP:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: OWASP
          command: |
            ./gradlew dependencyCheckAnalyze --info
workflows:
  version: 2.1
  Full build without itests:
    jobs:
      - Full build without itests
#  OWASP:
#    jobs:
#      - OWASP